name: Build
on: [ pull_request, push, workflow_dispatch ]
env:
  GH_USER: MTR-Offline-System-Map
  GH_REPO: example
  GH_PATH: /v2/
  GH_BRANCH: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Node packages
        run: npm ci
      - name: Build Angular (English)
        run: bash build.sh
      - name: Capture English build artifact
        uses: actions/upload-artifact@main
        with:
          name: English
          path: dist/osm/en-US/
      - name: Capture Simplified Chinese build artifact
        uses: actions/upload-artifact@main
        with:
          name: Simplified Chinese
          path: dist/osm/zh-Hans/
